const datadetails = [
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
    {
        id: 1,
        name: '',
        img1: '',
        img2: '',
        img3: '',
        title: '',
        Display: '',
        Resolution: '',
        Backlight_Technolog: '',
        HDR: '',
        Color: '',
        Processor: '',
        Motion: '',
        Sound: '',
        price: '',
    },
]